### ISSUE TITLE
Install Script with Redis could be further automated

### ISSUE THREAD

**Issue by tony-shannon** [RippleOSI/Ripple-Qewd#11]
There are a few steps in the install script for Redis that could be automated, including default values and the IPtables config steps

See images to explain;
![setup_qewd-ripple-redis_b](https://cloud.githubusercontent.com/assets/939996/22458204/499c2dfc-e793-11e6-84d2-c98fa5c653aa.jpg)

**Comment by robtweed** [comment]
The ipTables mechanism is no longer used, because nginx is now used as a proxy.  The only manual steps left are the Redis settings

**Comment by tony-shannon** [comment]
thanks @robtweed 
any way to automate those redis steps?
Thanks
T

**Comment by robtweed** [comment]
Just tested the way this can be done, and it will be included in the next build.

**Comment by robtweed** [comment]
Included in build 2.27 installer - now fully automated

**Comment by tony-shannon** [comment]
many thanks @robtweed
