### ISSUE TITLE
Referrals not available on EtherCIS

### ISSUE THREAD

**Issue by DineshPatelLeidos** [RippleOSI/Ripple-Qewd#22]
Referrals only available on Marand at present.
Refer to comment: 
[https://rippleosi.atlassian.net/browse/QEWD-19?focusedCommentId=22600&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22600](https://rippleosi.atlassian.net/browse/QEWD-19?focusedCommentId=22600&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22600)
EtherCIS will require further work.

**Comment by robtweed** [comment]
I believe that this was fixed - referrals from both Marand and Ethercis are returned

**Comment by PhilBarrett** [comment]
Confirmed as working
