### ISSUE TITLE
How can I use WebRTC function?

### ISSUE THREAD

**Issue by ZuzooVn** [RippleOSI/Ripple-Qewd#25]
Hi Ripple Team @robtweed @tony-shannon 

As I can see, you already had the webRTC function (Build 1.25.2) and Build 2.17: New installer includes WebRTC and nginx proxy.

But I can not find the Appointment function in the menu and webRTC function. I remember that we have Appointment function at http://demo.rippleosi.org/#/charts.
So, how can I use Appointment  & WebRTC function?

Thanks

**Comment by ZuzooVn** [comment]
@robtweed @tony-shannon 
I think you should take a look at  webRTC solution: https://github.com/jitsi/jitsi-meet

**Comment by tony-shannon** [comment]
thanks @ZuzooVn 

The Appointment function is now available within the Events Heading of the Patient Record
See here
![image](https://cloud.githubusercontent.com/assets/939996/25240269/4cfc8e84-25ea-11e7-9650-9cc6001aa1be.png)

The latest installer helps with the WebRTC install too, but as the WebRTC functionality needs an authenticated user (via OAuth2) and SSL setup .. this is a more complicated setup than the simple demo setup out of the box.
One issue ; were using auth0.com as an OAuth2 provider, but you would need to set up your own account and register the callback URLs for the server that you have setup.
This is non trivial stuff and we dont expect the average user to be able to spin this up easily.. expect you may need help with this aspect of the stack.. we are considering how we tidy this up/make this easier/cut this aspect out of the demo stack.

Hope that helps
Tony

**Comment by ZuzooVn** [comment]
Thank @tony-shannon for your information.

Currently, I just want to use your great RippleOSI for the production environment. 

I used secure mode but I always log in as 'Bob Smith' or user with ID '9999999000'.
Do you have any recommendation for login and webRTC function in secure mode for production environment?

Btw, when will you commit your latest source code (showcase1, demo server) to Github?

Thanks

**Comment by tony-shannon** [comment]
OK @ZuzooVn  you are one step ahead of us..

The current WebRTC functionality in the Ripple showcase stack is within the secure demo, but not deployed to production yet.

So any user that logs into the Ripple showcase in secure mode will end up as either Bob Smith (non gmail email = assigned IDCR role) or Ivor Cox  ID '9999999000' ( if gmail signin= assigned PHR user) .
IDCR Integrated Digital Care Record user is the Professional end
PHR Personal Health Record is the Patient end
if you look into the codebase for IDCR, PHR users at UI and middleware end, you may see the logic that assigns the identities etc and may be able to suggest ways to improve them
 

Bear in mind that the Ripple stack is combining 3 key tools (PulseTile UI framework) , QEWD (Middleware/Integration Framework ) and EtherCIS (Clinical Data Repository), aiming at multiple uses..
The WebRTC functionality is one part of that, works well in secure demo, but needs some work to get into production mode.

BTW the latest source code from Showcase1.rippleosi.org should be on Github already.. is there something you're not seeing?

thanks

**Comment by tony-shannon** [comment]
It looks like the install script may be the issues 
See lines 187-189 here
https://github.com/RippleOSI/Qewd-Ripple/blob/master/installer/install_ripple_redis.sh

For now, swap the comment out and the installer should pull in latest version from develop branch

# wget -O ripple_ui.zip https://github.com/PulseTile/PulseTile/blob/develop/build/ripple-latest.zip?raw=true

wget -O ripple_ui.zip https://github.com/PulseTile/PulseTile/blob/master/build/ripple-latest.zip?raw=true 

We'll update the master branch asap
thanks
Tony

**Comment by tony-shannon** [comment]
the master branch should now be updated
Tony

**Comment by ZuzooVn** [comment]
Thanks @tony-shannon 
I got the latest source code. 

> The WebRTC functionality is one part of that, works well in secure demo, but needs some work to get into production mode.

I start appointment between Bob Smith and Ivor Cox via this URL
http://showcase1.rippleosi.org/videochat/videochat.html?appointmentId=00873ad9-2c74-46e8-aa77-2ab7997feb48

- Chrome:  camera, voice, chat do not work with HTTP. I understand that it's the Chrome problem. 
```
adapter.js:1025 getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

videochat.js:175 Error: Cannot cam+mic or only mic devices stream
    at getAnyUserMediaStream (videochat.js:58)
    at videochat.js:63

errorHandler @ videochat.js:175
:8070/socket.io/?EIO=3&transport=polling&t=LkU7hhA Failed to load resource: net::ERR_INSECURE_RESPONSE

```

- Firefox: I can display the webcam, my friend log in as Ivor Cox in another laptop as well. We can't see each other, only ourself. 

![screen shot 2017-04-24 at 11 34 56 am](https://cloud.githubusercontent.com/assets/1429230/25322613/b5e5898c-28e2-11e7-84ed-7266fb5d5fc0.png)

Do you have any suggestion?
Thanks.

**Comment by tony-shannon** [comment]
@ZuzooVn 
I'm afraid you're struggling with the auth0 , https, SSL config aspects of this, as well as the fact that as I said the WebRTC functionality currently "needs some work to get into production mode".

This code is open source for many reasons and you are welcome to use it and improve it, but it looks like to do what you have in mind you'll need to consider a support contract. If this is something you want to progress let us know, we can put you in contact with a support service provider.

regards
Tony

**Comment by ZuzooVn** [comment]
Thanks @tony-shannon 
Does this mean the WebRTC work like a charm on your demo/showcase1 server?
Btw, do you have any plan to support WebRTC on Mobile application?

Thanks

**Comment by tony-shannon** [comment]
Yes the webrtc aspects work well within our demo showcase.
See earlier version in testing here
http://rippleosi.org/open-source-telehealth/

The main use we expect initially/have tested for would be in desktop
environment. My understanding is that the webRTC approach we're using may
not work easily within a mobile web environment and we might need to do
native app development is we wanted to support that requirement...
.. not a priority for us, just at the moment to be honest.

As you'll have noted the functionality in the application is broad and
wide..so the WebRTC aspect is just one small part.

Tony

**Comment by ZuzooVn** [comment]
Thank @tony-shannon for valuable information.

Could you please tell me the way to test webRTC function on your demo showcase?
Currently, I can only log in as Bob Smith.

Regards,

**Comment by tony-shannon** [comment]
You'd need to login to the secure version of our demo environment which the
team use for demos.. sorry that is not available to you.

We've made all the source code openly available so others can review and
improve it , but if you cant figure out how to set up the secure version
yourself with auth0, ssl, https etc.. you're going to be limited to the
open>secure demo version for now, until we get around to improving the
documentation to make it even easier to set up.

For now, if you have a project in mind you can consider getting support
arrangement for setup and further development of the the secure webRTC
version.
I did mention earlier that the WebRTC functionality is still non trivial to
set up.

**Comment by ZuzooVn** [comment]
Thanks Tony

+1 on everything you said.
What do you think about the possibility to integrate another WebRTC framework (https://github.com/jitsi/jitsi-meet) with Ripple?

**Comment by tony-shannon** [comment]
Can't see any driver to do that at present.
Feel free to experiment.
