### ISSUE TITLE
Can I get latest documentation for Qewd-Ripple?

### ISSUE THREAD

**Issue by ZuzooVn** [RippleOSI/Ripple-Qewd#26]
Hi @tony-shannon 

AFAIK, RippleOSI has below links for development documentation:

http://dev.rippleosi.org -> It can not access at the moment
http://rippleosi.org/document/technical-architecture/ -> It's out of date with Java Middleware. There is not any information about Node.JS Middleware.

Do you have any plan to update those documents?

Thanks

**Comment by tony-shannon** [comment]
thanks

You're right for pointing out that documentation needs updating.
We've removed those links.. thanks for pointing this out to us.

Please subscribe for repo updates here, if you want to check out the
revised documentation when its online.. we're progressing it as we speak
and will update here as/when ready for wider review..


Tony

**Comment by ZuzooVn** [comment]
Thanks Tony

Do you have estimated time of arrival?

Regards,

**Comment by tony-shannon** [comment]
approx 6 weeks
T

**Comment by ZuzooVn** [comment]
Thanks, I will keep this ticket open as the remaining ...

**Comment by ZuzooVn** [comment]
@tony-shannon : Do you have any early access for documentation? 
I would like to become your proofreader if you don't mind.

**Comment by tony-shannon** [comment]
Sure
Please sign into Google Docs to review the current documentation.
https://docs.google.com/document/d/1CQY6pU8vPUUFdLHKt1Q8W98IDKQQjKR7NnGt-3ME0tw/edit?usp=sharing
It will help me identify you and your comments.
thanks
Tony

**Comment by ZuzooVn** [comment]
Thanks, I logged in as Nam Vu.

**Comment by ZuzooVn** [comment]
Hi @tony-shannon 

AFAIK, RippleOSI integrated Orthanc Dicom from build 2.12 but I can not access the "Images" menu at the moment. I can not find any information about Orthanc in your documentation as well.

I found that code 

> <cornerstone-image imageId="http://138.68.134.7:8086/instances/{{item}}/preview"></cornerstone-image>

Is 138.68.134.7:8086 your Orthanc Dicom server?
When will you fix this problem?

Thanks,
Nam Vu from ThinkLabs-VN

**Comment by robtweed** [comment]
This should be fixed on new installations using the updated installer.

**Comment by tony-shannon** [comment]
@ZuzooVn 
Please see latest new documentation suite for our stack
http://docs-showcase.ripple.foundation/

Note also our new sites
http://ripple.foundation/
with links out to 
http://www.pulsetile.com/
http://qewdjs.com/
http://ethercis.org/

each with link to more detailed documentation

Let us know where the top 3 gaps are in your opinion

thanks
Tony
