### ISSUE TITLE
Transfer of Care middleware issues

### ISSUE THREAD

**Issue by dkryvosheya** [RippleOSI/Ripple-Qewd#28]
- [x] http://prntscr.com/f8er4z - when adding record for medications and/or Problems / diagnosis, we are getting the following error (see screenshot). 

- [x] http://prntscr.com/f8eq80 - NHS Choices is not being obtained through the query for Problems / Diagnosis record; 
  
- [x] Some records (like, for example, Avelox within Medications) - are not returning any data, but error (http://prntscr.com/f8er4z)
  
- [x] Same issue as described above, but for Referrals heading: http://prntscr.com/f8esah
  
- [x] Referral details is not returning the following data: http://prntscr.com/f8esri - Reason for referral and Clinical summary fields are missing within the obtained data; 
  
- [ ] http://prntscr.com/f8etcx - Events type and Events note are not being returned from the middleware either;
  
 - [x] Transfer of care seems have not yet been added to the middleware, so we don’t have any data to input to the read-only view - http://prntscr.com/f8eu1b; We see the Transfer of Care API returning empty string, and second query returns the "transfers-of-care has not yet been added to middle-tier processing’’ prompt.

**Comment by robtweed** [comment]
Could Dmitry review the outstanding ones please?  I believe that Transfer of Care is now working.  I'm not sure if others are now fixed?

**Comment by dkryvosheya** [comment]
@PhilBarrett @robtweed yes, marked everything that's implemented - the only item left (related to events);

**Comment by PhilBarrett** [comment]
That's great, thanks for the update. @robtweed if you'd prefer me to open this in a new issue, please let me know.

**Comment by robtweed** [comment]
Events is already covered by an open issue - which is awaiting agreement between Ian and Tony on how Events should work in detail.  This issue can therefore be closed IMO

**Comment by PhilBarrett** [comment]
https://github.com/RippleOSI/Ripple-Qewd/issues/33
