### ISSUE TITLE
Customize api for paging

### ISSUE THREAD

**Issue by maxcda101** [RippleOSI/Ripple-Qewd#31]
Hi Ripple Team,
I have a problem, that I have a medical device to automatically  push vitalsigns information up RippleOsi, so a lot of data is posted up.
When I call api `/api/patients/:idpatient/vitalsigns` to get the data, the data returns very slowly and many records.
So I want to customize the api to reduce load and paging, for example `/api/patients/:idpatient/vitalsigns?start=5&limit=10`
Then the result returned 10 records and started from order = 5, but I can not do it.
Also, I also want to customize for the other api: patients, procedures, events ....
Can the Ripple Team be customized to help me or have any other solution?

Thanks and Best Regards.
Quan Nguyen from ThinkLabs-VN

**Comment by tony-shannon** [comment]
thanks @maxcda101 
Sorry for delay on the reply here, we've been busy launching websites etc
See  http://ripple.foundation/ & links to sites for our Documentation plus PulseTIle, QEWD, EtherCIS & related documentation

We can offer to help but would need you to sponsor this work at the moment, its not a priority for us.

If you prefer to review the related code/documentation for this area and suggest an approach, we may be able to guide you as to a solution you can craft and then submit.

Hope that helps?
Tony

**Comment by maxcda101** [comment]
thanks Tony

On this issue I have resolved already.
But you should customize the api retrieve data from ethercis, when the data up very large will cause the system to slow down.

Quan Nguyen from ThinkLabs-VN

**Comment by tony-shannon** [comment]
thanks Quan Nguyen

You say resolved?
Is that something you're submitting a pull request on /need to discuss
further here?

re " customize the api retrieve data from ethercis" .. assume you mean on
the Qewd-Ripple side?
If so what changes do you suggest to the codebase?

thanks
Tony
