### ISSUE TITLE
QEWD - Clinical Queries not hooked up

### ISSUE THREAD

**Issue by dkryvosheya** [RippleOSI/Ripple-Qewd#32]
Clinical querying is not hooked up - Unable to perform clinical queries within the platform

**Comment by tony-shannon** [comment]
thanks @dkryvosheya 
Can you please split those out as separate issues, so we can manage & track them individually.
Thanks
T

**Comment by dkryvosheya** [comment]
@tony-shannon done, Tony

**Comment by tony-shannon** [comment]
Many thanks @dkryvosheya

**Comment by tony-shannon** [comment]
Is the clinical query function hooked up via the QEWD middleware, ready for Pulsetile yet?

**Comment by robtweed** [comment]
Awaiting information from Dmitry. Skype is down today

**Comment by robtweed** [comment]
Advanced search is done. Just clinical search to do now

**Comment by robtweed** [comment]
Clinical Search is ready in the middle tier.  Looks like Christian sorted out the AQL parsing on Ethercis, so it appears to return expected results.  However, still awaiting the UI changes to make it send the correct request payload

**Comment by PhilBarrett** [comment]
@robtweed @dkryvosheya thanks for this, working as intended after review by PB/TS.
