### ISSUE TITLE
QEWD - Clinical statements heading returning empty values

### ISSUE THREAD

**Issue by dkryvosheya** [RippleOSI/Ripple-Qewd#34]
Clinical statements heading - After creating a new clinical statement it doesn't store the new entry (not a refresh issue). http://prntscr.com/fhbywy - Clinical statement retuns an empty value from the middleware level for some reason, without an ability to create a statement as well (dropdowns which are populated from the source are empty as well - http://prntscr.com/fhbzj5)

**Comment by robtweed** [comment]
Clinical Statements should now be working - can you confirm?

**Comment by tony-shannon** [comment]
Yes thanks @robtweed , just checked and working ok now.

Can you please provide URL & details for the clinical Statements authoring tool here please, I need to update the related documentation
Are you hosting it seperately or part of the Ripple install stack?

I can close this issue off then.

thanks
Tony

**Comment by robtweed** [comment]
The clinical statements authoring (aka content store) facility is automatically installed and enabled for anyone installing Ripple-Qewd.  Point the browser at the URL:

/qewd-content-store/index.html

(ie after the server domain name/IP)

Username can be anything you like (it's ignored but has to contain something)
Password is your qewd-monitor management password (by default: keepThisSecret!  You can change it in the ripple-demo.js and ripple-secure.js startup files

**Comment by tony-shannon** [comment]
thanks @robtweed
