### ISSUE TITLE
QEWD General - Browser refresh issue

### ISSUE THREAD

**Issue by dkryvosheya** [RippleOSI/Ripple-Qewd#35]
Refreshing screen takes you back to the business intelligence landing screen - When you click to refresh the content, it should bring you back to the patient and screen you were wishing to refresh, instead it takes you back to the landing screen at the business intelligence view.

**Comment by robtweed** [comment]
Isn't this a UI (PulseTile) issue?

**Comment by tony-shannon** [comment]
thanks @robtweed , Im unsure if it us

For instance if I hit a particular url in the browser eg
http://dev1.ripple.foundation/#/patients/9999999000/allergies/a4192017-952b-406b-9dab-cde79b20e82e?page=1&source=ethercis
then it brings me back to the landing page/clinical intelligence view

So something is always forcing the user back to the landing page
If you want to explain why you think its a PulseTile issue I can ask Dmitry to take it back and resolve this there...

thanks
Tony

**Comment by robtweed** [comment]
The middle tier has no direct control over the UI - it simply responds to the REST APIs it is sent.  In this case, when I tried it, the UI sent 2 allergy requests:

http://dev1.ripple.foundation/api/patients/9999999000/allergies

followed by one for the specific composition ID:

http://dev1.ripple.foundation/api/patients/9999999000/allergies/a4192017-952b-406b-9dab-cde79b20e82e?source=ethercis

Why the UI sends these requests as a result of pasting in that URL is a UI issue, and what the UI does as a result of the responses sent by the middle tier for these requests is, again, up to the UI.

I don't see how this can be a Ripple-Qewd issue

**Comment by dkryvosheya** [comment]
@robtweed However, on the other hand - the token should be obtained in order to view the page - on the other hand, user will end up seeing this error message: 
![image](https://user-images.githubusercontent.com/26797687/27280399-7190264a-54f0-11e7-974d-4791c18a30ea.png) - so, in order to implement this feature we should send a request to /api/initialize (as far as I remember) every time the browser requests particular heading? 
Since, there is no other way from my personal perspective - any ideas on this, Rob?

**Comment by robtweed** [comment]
The middle tier, when asked for patient details, will (and must) check the JSESSIONID token to ensure it is still valid.  If not, it will return an error response - as above.  It's up to the UI to then determine what to do if the token has expired.  The middle tier doesn't control the UI directly in terms of if, how and where it redirects itself

**Comment by dkryvosheya** [comment]
@tony-shannon we may need to have your input on the issue above; 
How should the app behave if the JSESSIONID token expired and/or missing?

**Comment by dkryvosheya** [comment]
Me and Rob discussed this item - we do have a solution for this: 
If UX sees that token is expired / missing, while loading the page - we will ask middleware for token, and after that we will proceed to the requested page of the app. Closing the issue.

**Comment by PhilBarrett** [comment]
Thanks @dkryvosheya that sounds very positive. Let's close the issue once the fix is in place, cheers

Phil

**Comment by tony-shannon** [comment]
agreed @PhilBarrett 
thanks @dkryvosheya  and @robtweed 
Look forward to seeing that suggested fix in action and then retesting this
Tony

**Comment by tony-shannon** [comment]
@Rob confirms not a QEWD issue, this is UI related issue
