### ISSUE TITLE
Build fails on Ubuntu using install_ripple_gtm.sh script

### ISSUE THREAD

**Issue by Geisterfalle** [RippleOSI/Ripple-Qewd#36]
When building Qewd on a freshly installed Ubuntu 16.04 I get the following error when using the install_ripple_gtm.sh script:

--2017-06-13 12:51:31--  https://github.com/PulseTile/PulseTile/blob/master/build/ripple-latest.zip?raw=true
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-06-13 12:51:32 ERROR 404: Not Found.

Consequently, the content store, monitor seem to work but the front end built on Pulse Tile is not installed.

**Comment by maxcda101** [comment]
You edit the link to `https://github.com/PulseTile/PulseTile/blob/master/build/PulseTile-latest.zip?raw=true` in file `install_ripple_gtm.sh`

**Comment by robtweed** [comment]
The installers are now fixed to use the renamed UI source file

**Comment by tony-shannon** [comment]
thanks @robtweed 

thanks for helping out on this one @maxcda101 , appreciate it.

Tony
