### ISSUE TITLE
QEWD - MDT - Service / team data is not populated

### ISSUE THREAD

**Issue by dkryvosheya** [RippleOSI/Ripple-Qewd#37]
http://prntscr.com/fhc79t - comes as an empty value from middleware - should be sorted out on marand / ethercis level;

**Comment by tony-shannon** [comment]
Please log as qewd-ripple related issue then
T

**Comment by robtweed** [comment]
MDT is now working.  Included in build 2.27 installer.  Installed and working on dev and demo machines

**Comment by PhilBarrett** [comment]
Thanks @robtweed , working my side too.
