### ISSUE TITLE
Decimal counts data

### ISSUE THREAD

**Issue by dkryvosheya** [RippleOSI/Ripple-Qewd#41]
Rob, can you please investigate why the UI gets the following data as decimal? http://prntscr.com/fna1z1
Thanks!

**Comment by robtweed** [comment]
This appears to be a strange Ethercis-related issue.  Sometimes it returns counts as integers, sometimes as real numbers.  I can convert them at the middle tier level of course, but I think we need Christian/Ian to figure out what's happening

**Comment by tony-shannon** [comment]
thanks Rob & agree needs resolving in EtherCIS
thanks
T

**Comment by PhilBarrett** [comment]
Rob has confirmed this is now resolved.
