### ISSUE TITLE
openEHR AQL & test data updates - updates to mapping needed

### ISSUE THREAD

**Issue by tony-shannon** [RippleOSI/Ripple-Qewd#45]
@freshehr has updated the openEHR test data for this patient
https://github.com/RippleOSI/Ripple-openEHR/issues/6#issuecomment-311816397
NHS No 9999999068

we need to update Ripple-Qewd mappings as result, this will impact on older test data eg Ivor Cox but  we can accept that as part of move to tidy up the demonstrator

Personal Notes
Clinical Notes
missing 'Type' for patient and clinical notes- suspect mismatch in QEWD as the data is coming back ok

Medication - not displaying correctly due to updated template and implementation guide needs reworked in QEWD.

Lab orders - needed update to lab orders AQL which is now correct in the updated implementation guide

I understand the updated implementation guidance is available here
https://github.com/RippleOSI/Ripple-openEHR/tree/master/docs/bindings/markdown

**Comment by robtweed** [comment]
Personal Notes - The type is returned to the UI as the response property noteType and appears to work OK for me for 9999999068.  The mappings look OK to me so I'm not sure what problem I'm looking for

**Comment by tony-shannon** [comment]
thanks @robtweed 
@freshehr can you comments on the Personal Notes one from your view?

**Comment by robtweed** [comment]
I couldn't see any change in the Personal Notes AQL from what is already in use

**Comment by robtweed** [comment]
Tony - can you give me an example I can replicate that demonstrates a problem with Personal Notes?  It looks like it works to me.

**Comment by robtweed** [comment]
Clinical Notes don't display the type because, I assume, it's not correctly using the response property which is "clinicalNotesType".  The clinicalNotesType is being correctly returned.  Either the UI needs to be changed to use this field, or Dmitry needs to tell me what field name he's expecting

**Comment by robtweed** [comment]
Again, the AQL for Clinical Notes hasn't been changed from the version currently in use

**Comment by tony-shannon** [comment]
Not seen a problem myself.

Can  @freshehr comment please?

**Comment by robtweed** [comment]
Medications - I've not yet updated as I need confirmation from Ian about the terminology field which appears to be missing from the AQL

**Comment by robtweed** [comment]
Lab Orders.  I'm confused by this.  The implementation details for lab_orders is dated January but seems to be slightly different from the version I was using in the middle tier.  The revised version (as per https://github.com/RippleOSI/Ripple-openEHR/blob/master/docs/bindings/markdown/Orders/lab_orders.md) appears to work OK against Ivor Cox (9999999000) but not against 9999999068.  Order name and date created are coming back as empty strings

**Comment by robtweed** [comment]
Update on Clinical Notes: Dmitry is going to change the UI to use the clinicalNotesType field which is being returned by the middle tier

**Comment by freshehr** [comment]
Patient notes: This does seem to be correct now.
Clinical notes - agree with proposed solution
Medications - I have given Rob the updated AQL to fix the terminology issue.
Lab orders - investigating

**Comment by robtweed** [comment]
Awaiting UI fix for clinical notes - it needs to pick up the type as "clinicalNotesType"

**Comment by robtweed** [comment]
Medications OpenEHR data retrieval:  no data is being retrieved for dose directions.  Dose Timing seems to duplicate the date in Dose Amount.  Ian - could you investigate?

**Comment by freshehr** [comment]
Dose directions sample data was just missing - have added some dummy data now. BTW I suggest changing this to "Additional instructions" which lines up much better with openEHR, PRSB and FHIR.

The queries are definitely returning Dose Timing and Dose amount correctly - ? a mapping error in Rob's code?

```
 {
            "uid": "904a36b6-1f21-4979-9378-4036fc8412ce::ripple_osi.ehrscape.c4h::1",
            "dose_timing": "in the morning",
            "route": "oral",
            "medication_name_code": "15222008",
            "author": "Dr George Shaw",
            "date_created": "2016-02-24T00:11:02.518+02:00",
            "dose_amount": "10mg",
            "dose_directions": "Take before food",
            "medication_name": "Enalapril",
            "start_date": "2016-02-24T10:50:42Z"
        }
```

**Comment by tony-shannon** [comment]
@robtweed tells me hes using the AQL as documented.
Yet the dose amount & dose timing are sometimes returning the same values.. ie the amount.

@robtweed  will give an example shortly..

**Comment by PhilBarrett** [comment]
@tony-shannon tested, working fine, thanks all.
