### ISSUE TITLE
Events - single POST creates two event instances;

### ISSUE THREAD

**Issue by dkryvosheya** [RippleOSI/Ripple-Qewd#49]
Referring https://github.com/PulseTile/PulseTile/issues/23 

Single POST request to create an Event (http://prntscr.com/g0dvzs), as a result, creates two identical event instances.

**Comment by robtweed** [comment]
Should be working properly now - this was a residual issue resulting from the recent re-coding to use cached OpenEHR sessions.

**Comment by PhilBarrett** [comment]
Tested just now on dev environment, working as intended. Thanks @robtweed
