### ISSUE TITLE
Redis cache returns null.

### ISSUE THREAD

**Issue by linto17** [RippleOSI/Ripple-Qewd#52]
In patient summary, dashboards won't show anything and if opened that module this will show undefined or rows with blank values.
I need to clear the Redis cache manually to solve this problem.
please help.

**Comment by robtweed** [comment]
The Redis cache is used for logged-in users who have previously fetched data.  If you log out (or manually clear the JSESSIONID cookie from your browser), then it will fetch the data again from the OpenEHR systems and re-cache it

**Comment by linto17** [comment]
Thanks.
