### ISSUE TITLE
change static information to the dynamic one from Patient Info drop-down

### ISSUE THREAD

**Issue by anna-otrokhova** [RippleOSI/Ripple-Qewd#59]
Change static information to the dynamic one, it will be displayed in the Patient Info drop-down, potentially to the "application" endpoint. http://prntscr.com/gyzb6p 
Here should be displayed the actual information about the version.

This issue is linked to this one: PulseTile/PulseTile#47
https://github.com/PulseTile/PulseTile-React/issues/45

**Comment by tony-shannon** [comment]
Rob has updated this issue
https://github.com/PulseTile/PulseTile-React/issues/45#issuecomment-368926500

**Comment by tony-shannon** [comment]
this issue can be closed in this qewd-ripple repo
