### ISSUE TITLE
Empty string values are present in DB, the records which have such fields can't be edited

### ISSUE THREAD

**Issue by anna-otrokhova** [RippleOSI/Ripple-Qewd#62]
There are some records, which were added as testing data I suppose manually. These records have empty fields by default and these fields are usually static (so when we create a new Allergy, for example, we don't enter these fields) Once we edit something we take the information which already has empty string values .
1) I suppose such records should be removed from DB. 
2) And test data should be checked for empty fields (string values) before adding to DB.

this is an example of such record http://prntscr.com/h7tnyj
http://prntscr.com/h7to26
Could you check it, please

This issue is related to this one: https://github.com/PulseTile/PulseTile-React/issues/63

**Comment by tony-shannon** [comment]
thanks @anna-otrokhova 

Rob, this is a test data issue, perhaps the data came in from API or directly into the backends
Can you take a look and advise how we manage & prevent please
thanks
T

**Comment by tony-shannon** [comment]
Hi @robtweed 
We will need to go over key headings to tidy up these items in prep for go live

**Comment by tony-shannon** [comment]
lets close this for now , as not been a problem of late
